name: thztools
channels:
  - defaults
  - conda-forge
dependencies:
  - sphinx
  - pydata-sphinx-theme
  - numpy
  - scipy
  - pandas
  - mpmath
  - setuptools >= 65.5.1
  - flake8
  - pytest-cov
  - matplotlib
  - click
  - ipython
  - coverage
  - python-dotenv
  - jupyter
  - h5py
  - pip
  - pip:
    - -e .