[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "thztools"
dynamic = ["version"]
description = "Data analysis tools for terahertz time-domain spectroscopy (THz-TDS)"
readme = "README.md"
license = "MIT"
keywords = ["terahertz", "THz", "time-domain spectroscopy", "data analysis"]
authors = [
  { name="Steve Dodge", email="jsdodge@sfu.ca" },
  { name="Santiago Higuera Quintero", email="s.higuera@uniandes.edu.co" },
  { name="Jonathan Posada", email="jonathan.posada1@udea.edu.co" },
]
maintainers = [
  { name="Steve Dodge", email="jsdodge@sfu.ca" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "pandas",
    "scipy",
]

[project.urls]
Documentation = "https://pages.github.com/dodge-research-group/thztools"
Issues = "https://github.com/dodge-research-group/thztools/issues"
Source = "https://github.com/dodge-research-group/thztools"

[tool.hatch.version]
path = "tests/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
    "/tests",
]
